services:
    cms.authentication_success_listener:
        class: App\EventListener\AuthSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
