security:
    encoders:
        App\Entity\Person:
            algorithm: argon2i
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Person
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false
        login:
            pattern: ^/authentication_token
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api_register:
            pattern: ^/people
            methods: [POST]
            stateless: true
            anonymous: true
        api:
            pattern: ^/
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/people, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST]}
