vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /media/user_avatar
            upload_destination: '%kernel.project_dir%/public/media/user_avatar'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
